server:
  port: 8081
  servlet:
    context-path: /neo-service

spring:
  profiles:
    active: dev,service

mybatis:
  type-aliases-package: com.xsw.neo.service.model.entity
  mapper-locations: classpath*:com/xsw/neo/service/mapper/xml/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:log4j2.xml
  level:
    com.xsw.neo.service.mapper: trace
